name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create html_files directory on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_H0ST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/html_files

      - name: Copy files via SCP to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_H0ST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "image.html,sample_image.png"
          target: "/home/ubuntu/html_files"

      - name: Copy files to Web Directory
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_H0ST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo cp -r /home/ubuntu/html_files/* /var/www/html/
            sudo systemctl restart apache2 || sudo systemctl restart httpd || true